baseURL = "http://dexterposh.github.io/"
languageCode = "en-us"
title = "Notes from a system engineer's desk"
theme = "m10c"
publishDir = "dexterposh.github.io"


[params]
  author = "Deepak Singh Dhami"
  description = "Dev?Ops"

  [[params.social]]
    name = "github"
    url = "https://github.com/dexterposh"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/dexterposh"

  [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"