baseURL = "https://dexterposh.github.io/"
languageCode = "en-us"

title = "System Engineer taking Dev?Ops notes"
theme = "hyde-hyde"

paginate = 5
publishDir = "dexterposh.github.io"
googleAnalytics = "UA-165270256-1"
enableEmoji = true
summarylength = 30

[params]
  author = "Deepak Singh Dhami"
  title = "DexterPOSH"
  description = "Cloud, Servers & Code."
  authorimage = "avatar.jpg"
  dateformat = "Jan 2, 2006"

  # https://highlightjs.org
  highlightjs = true
  highlightjsstyle = "github"

  # Table of contents
  toc = "hugo"

[params.social]
    github = "https://github.com/dexterposh"
    twitter = "https://twitter.com/dexterposh"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"