baseURL = "https://dexterposh.github.io/"
languageCode = "en-us"

title = "System Engineer taking Dev?Ops notes"
theme = "hyde-hyde"

paginate = 5
publishDir = "dexterposh.github.io"
googleAnalytics = "UA-165270256-1"
enableEmoji = true
summarylength = 30

[permalinks]
  fixed = ":title"

[params]
  author = "Deepak Singh Dhami"
  title = "DexterPOSH"
  description = "Cloud, Servers & Code."
  authorimage = "avatar.jpg"
  dateformat = "Jan 2, 2006"
  highlightjs = true
  highlightjsstyle = "github"

  # Table of contents
  toc = "hugo"
  NewsletterSignup = "https://tinyletter.com/DexterPOSH"

[params.social]
    github = "dexterposh"
    twitter = "dexterposh"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "Subscribe"
    weight = 99
    identifier = "Subscribe"
    url = "/Subscribe/"
[[menu.main]]
    name = "About"
    weight = 1
    identifier = "About"
    url = "/About/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"