baseURL = "https://dexterposh.github.io/"
languageCode = "en-us"
title = "Notes from a system engineer's desk"
theme = "hyde"
paginate = 5
publishDir = "dexterposh.github.io"
googleAnalytics = "UA-165270256-1"
enableEmoji = true

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/dexterposh"},
      {Name = "Twitter", URL = "https://twitter.com/dexterposh"}
  ]

[params]
  author = "Deepak Singh Dhami"
  description = "Dev?Ops"
  themeColor = "theme-base-0d"
  layoutReverse = true